name: Auto-Sync

on:
  push:
    branches:
      - main

jobs:
  sync-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # needed for full history

      - name: Configure Git
        run: |
          git config user.name "${{github.actor}}"
          git config user.email "${{github.actor}}@users.noreply.github.com"

      - name: Merge main into staging
        run: |
          git fetch origin staging
          git checkout staging
          git merge origin/main --no-edit
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} staging
